### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by ssepa001** [brunolemos/parse-sdk#1]
Hello,

First I wanted to thank you for making this repo and keeping it up to date. Please feel free to message me to tell me how I can help keep this Git updated as I am using meteor and Parse on a big project so I am very interesting in helping keeping this repo updated.

That said is it possible to update the SDK to the newer 1.9.x version ?

Thanks,
Sam

**Comment by brunolemos** [comment]
Hi @ssepa001, thanks, just updated to v1.9.1!
Feel free to make a pull request in the future.

But just out of curiosity, why don't you use npm? 
Is your meteor version older than 1.3?

@brunolemos.

**Comment by ssepa001** [comment]
Great thanks.
I am not sure, I am using 1.3. Is there an official npm package by Parse ?
Sam

**Comment by brunolemos** [comment]
Yes, try running:
`meteor npm install parse`
